language: python3
sudo: enabled
python:
    - 3.6
before_install:
    - sudo apt-get install python3-pip
    - sudo apt-get install python3-flake8
install:
    - pip3 install --user -r requirements.txt
script:
    - flake8 *.py
    - python3 -m unittest

